import os
import re
import time
from urllib.parse import urlparse, urlunparse

import requests


WP_URL = os.environ.get("WP_URL", "http://localhost:8080")
WP_BACKEND_URL = os.environ.get("WP_BACKEND_URL", "http://wordpress")
API_BASE = f"{WP_BACKEND_URL}/wp-json/test/v1"
_parsed = urlparse(WP_URL)
HOST_HEADER_VALUE = "localhost:8080" if _parsed.hostname == "varnish" else _parsed.netloc


def _host_headers():
    return {"Host": HOST_HEADER_VALUE}


def _to_container_url(u: str) -> str:
    orig = urlparse(u)
    dest = urlparse(WP_URL)
    return urlunparse((dest.scheme, dest.netloc, orig.path, orig.params, orig.query, orig.fragment))


def _new_session():
    s = requests.Session()
    s.headers.update(_host_headers())
    return s


def _login_admin(sess: requests.Session):
    sess.get(f"{WP_URL}/wp-login.php", allow_redirects=False)
    data = {
        "log": "admin",
        "pwd": "admin",
        "wp-submit": "Log In",
        "redirect_to": f"{WP_URL}/wp-admin/",
        "testcookie": "1",
    }
    r = sess.post(f"{WP_URL}/wp-login.php", data=data, allow_redirects=False)
    assert r.status_code in (302, 303), f"login failed: {r.status_code}"


def head(url: str):
    r = requests.head(url, headers=_host_headers(), allow_redirects=False)
    r.raise_for_status()
    return r


def header(r, name: str) -> str:
    return r.headers.get(name)


def test_adminbar_real_link_purges_no_trailing_slash():
    # Use no-trailing-slash permalinks
    r = requests.post(f"{API_BASE}/permalinks", json={"structure": "/%postname%"}, headers=_host_headers())
    r.raise_for_status()

    # Create a post
    c = requests.post(f"{API_BASE}/post", json={}, headers=_host_headers())
    c.raise_for_status()
    data = c.json()
    url = _to_container_url(data["url"]).rstrip('/')

    # Warm cache
    r0 = head(url)
    assert header(r0, "X-Cache") == "MISS"
    time.sleep(0.2)
    r1 = head(url)
    assert header(r1, "X-Cache") == "HIT"

    # Login and fetch the page as admin to get the adminbar link
    sess = _new_session()
    _login_admin(sess)
    page = sess.get(url, allow_redirects=False)
    assert page.status_code in (200, 301, 302, 304), f"unexpected status {page.status_code}"

    # Extract the purge link generated by the plugin adminbar
    # It should contain the vhp_flush_do param and a nonce
    m = re.search(r'href=["\']([^"\']*vhp_flush_do[^"\']*)["\']', page.text)
    assert m, "adminbar purge link not found"
    href = m.group(1)
    href = _to_container_url(href)

    # Click the link (nonce-protected) as the admin user
    resp = sess.get(href, allow_redirects=False)
    # Some themes redirect; tolerate 2xx/3xx
    assert resp.status_code in (200, 301, 302, 303, 304), f"purge href status {resp.status_code}"

    # Expect MISS after a short delay
    hit_miss = None
    for _ in range(10):
        time.sleep(0.4)
        r2 = head(url)
        hit_miss = header(r2, "X-Cache")
        if hit_miss == "MISS":
            break
    assert hit_miss == "MISS", "Expected MISS after clicking adminbar purge link"


